# Autres variables en clair
db_name: mon_app_db
db_user: admin_user

vault_db_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35656134343865333834643737363530366239306163346335396434383733323835336262626233
          3430323137343662653366313837646465326535353332650a383332366565666164383464623535
          32373630313739373435616533663065616139626661343332366362333038386466646162336165
          6433626565616264620a623262663062306332336134373061303366383437396137396161373035
          3839