# Nom de la base de données
db_name: mon_app_db

# Identifiants de l'utilisateur
db_user: admin_user
db_password: "password_provisoire"  # 

# Configuration réseau (optionnel pour l'instant)
db_port: 5432